In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
from sklearn.model_selection import train_test_split

In [19]:
os.getcwd()

'E:\\SLIIT-research\\Project\\notebooks'

### Load the dataset

In [20]:
# df = pd.read_csv('..\\data\\final_dataset.csv')

In [21]:
# train, test = train_test_split(df, test_size=0.3, random_state=42, stratify=df['Label'])

In [22]:
# train.to_csv('..\\data\\train.csv', index=False)

In [23]:
# test.to_csv('..\\data\\test.csv', index=False)

In [24]:
# train['Label'].value_counts()

In [25]:
# test['Label'].value_counts()

In [26]:
from preprocessing.training_pipeline import DataPreprocessingPipeline

In [27]:
pipeline = DataPreprocessingPipeline()

In [28]:
# train_y = train['Label']
# train_X = train.drop(columns='Label')

In [31]:
# train = pd.read_csv('..\\data\\train.csv')
# train_y = train['Label']
# train_X = train.drop(columns='Label')

In [ ]:
# sampled = train_X.sample(frac=0.1)

### Chunking code

In [29]:
# for chunk in pd.read_csv('..\\data\\train.csv', chunksize=10000):
#     pipeline.partial_fit(chunk)

In [30]:
# for i, chunk in enumerate(pd.read_csv('..\\data\\train.csv', chunksize=10000)):
#     chunk_y = chunk['Label']
#     chunk_X = chunk.drop(columns='Label')
#     transformed_chunk_y = chunk_y.map({'Benign': 0, 'ddos': 1})
#     transformed_chunk_X = pipeline.transform(chunk_X)
#     transformed_df_y = pd.DataFrame(transformed_chunk_y, columns=['Label'])
#     transformed_df_X = pd.DataFrame(transformed_chunk_X, columns=chunk.columns)
#     
#     
#     if i == 0:
#         transformed_df_X.to_csv('..\\data\\train_transformed_X.csv', index=False)
#         transformed_df_y.to_csv('..\\data\\train_transformed_y.csv', index=False)
#     else:
#         transformed_df_X.to_csv('..\\data\\train_transformed_X.csv', mode='a', header=False, index=False)
#         transformed_df_y.to_csv('..\\data\\train_transformed_y.csv', mode='a', header=False, index=False)

hi
hi
testing

RuntimeError: The transformer has not been fitted yet.

### Individually running preprocessing due to memory issues

In [2]:
# train = pd.read_csv('..\\data\\train.csv')

In [4]:
# train_y = train['Label']
# train_X = train.drop(columns='Label')

In [3]:
from preprocessing.composite_splitter import CompositeSplitter
from preprocessing.feature_dropper import FeatureDropper
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [5]:
# dropped_train_X = FeatureDropper().transform(train_X)

In [6]:
# composite_dropped_train_X = CompositeSplitter().transform(dropped_train_X)

hi
hi

In [7]:
# composite_dropped_train_X.to_csv('..\\data\\train_composite_dropped_X.csv', index=False)

In [4]:
composite_dropped_train_X = pd.read_csv('..\\data\\train_composite_dropped_X.csv')

In [7]:
cleaned_X = composite_dropped_train_X[~composite_dropped_train_X.isin([np.nan, np.inf, -np.inf]).any(axis=1)]

In [8]:
cleaned_X.to_csv('..\\data\\train_cleaned_X.csv', index=False)

In [9]:
scaler.fit(cleaned_X)

StandardScaler()

In [10]:
import pickle
with open('..\\preprocessing\\scaler.pkl','wb') as f:
    pickle.dump(scaler, f)

In [11]:
scaled_X = scaler.transform(cleaned_X)

In [13]:
pd.DataFrame(scaled_X).to_csv('..\\data\\train_scaled_X.csv', index=False)

In [2]:
scaled_X = pd.read_csv('..\\data\\train_scaled_X.csv')

In [3]:
scaled_X.head()

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
0,-1.460424,1.788149,-0.435883,-0.332546,-0.015337,-0.016871,-0.020606,-0.006320,-0.745688,-0.360506,...,-0.258904,-0.250723,-0.923676,1.342814,0.596322,0.584761,0.613090,-0.690405,-0.294225,-0.319048
1,0.542384,-0.627486,-0.435883,-0.332515,-0.014190,-0.004096,-0.017710,-0.005360,-0.336517,-0.360506,...,-0.258904,-0.250723,0.716066,-0.790015,-0.444773,0.477156,0.569185,1.895365,1.223941,3.174248
2,0.743098,-0.627486,-0.435883,-0.332491,-0.015337,-0.016871,-0.020606,-0.006320,-0.745688,-0.360506,...,-0.258904,-0.250723,-1.388270,1.342814,-1.117481,-0.294013,0.613090,-0.690405,-0.235834,-0.350238
3,-1.474846,1.389573,-0.435883,-0.131811,-0.013617,0.000162,-0.003787,-0.005700,1.630553,-0.360506,...,-0.258904,-0.250723,0.716066,-0.790015,-0.396723,-0.598894,-1.640728,1.489527,1.574288,-0.474998
4,1.090930,-0.628660,2.175036,-0.330130,-0.014763,-0.012612,-0.018052,-0.005537,-0.565246,3.231901,...,-0.258904,-0.250723,0.716066,-0.790015,-0.428756,0.692366,0.613090,-0.690405,-1.243080,-0.755710

In [4]:
scaled_X.shape

(8922690, 87)

In [5]:
sampled_20e3 = scaled_X[:20000].reset_index(drop=True)

In [6]:
sampled_20e3.to_csv('..\\data\\train_scaled_X_20e3.csv', index=False)

In [7]:
sampled_20e3.head()

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
0,-1.460424,1.788149,-0.435883,-0.332546,-0.015337,-0.016871,-0.020606,-0.006320,-0.745688,-0.360506,...,-0.258904,-0.250723,-0.923676,1.342814,0.596322,0.584761,0.613090,-0.690405,-0.294225,-0.319048
1,0.542384,-0.627486,-0.435883,-0.332515,-0.014190,-0.004096,-0.017710,-0.005360,-0.336517,-0.360506,...,-0.258904,-0.250723,0.716066,-0.790015,-0.444773,0.477156,0.569185,1.895365,1.223941,3.174248
2,0.743098,-0.627486,-0.435883,-0.332491,-0.015337,-0.016871,-0.020606,-0.006320,-0.745688,-0.360506,...,-0.258904,-0.250723,-1.388270,1.342814,-1.117481,-0.294013,0.613090,-0.690405,-0.235834,-0.350238
3,-1.474846,1.389573,-0.435883,-0.131811,-0.013617,0.000162,-0.003787,-0.005700,1.630553,-0.360506,...,-0.258904,-0.250723,0.716066,-0.790015,-0.396723,-0.598894,-1.640728,1.489527,1.574288,-0.474998
4,1.090930,-0.628660,2.175036,-0.330130,-0.014763,-0.012612,-0.018052,-0.005537,-0.565246,3.231901,...,-0.258904,-0.250723,0.716066,-0.790015,-0.428756,0.692366,0.613090,-0.690405,-1.243080,-0.755710

In [8]:
sampled_20e3.shape

(20000, 87)

In [9]:
train = pd.read_csv('..\\data\\train.csv')

In [10]:
train_y = train['Label']

In [12]:
sampled_20e3_y = train_y[:20000].reset_index(drop=True)

In [13]:
sampled_20e3_y.head()

0    Benign
1    Benign
2      ddos
3      ddos
4    Benign
Name: Label, dtype: object

In [16]:
sampled_20e3_y = sampled_20e3_y.map({'Benign': 0, 'ddos': 1})

In [17]:
sampled_20e3_y.head()

0    0
1    0
2    1
3    1
4    0
Name: Label, dtype: int64

In [18]:
sampled_20e3_y.to_csv('..\\data\\train_y_20e3.csv', index=False)